[project]
name = "ecommerce-api"
version = "0.1.0"
description = "E-Commerce platform with cart and payment gateway integration."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.5",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.17.1",
    "requests>=2.34.2",
    "ruff>=0.15.13",
]
